-- ============================================================
-- SCHEMA FINAL PROPRE - 3 Essieux Manager
-- Exécutez ce script APRÈS avoir nettoyé avec ANALYSE_SQL.md
-- ============================================================

-- ============================================
-- 1. HELPER FUNCTIONS (Pour éviter récursion RLS)
-- ============================================

CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TEXT
LANGUAGE SQL
SECURITY DEFINER
STABLE
SET search_path = ''
AS $$
  SELECT role FROM public.users WHERE id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.get_my_company_id()
RETURNS UUID
LANGUAGE SQL
SECURITY DEFINER
STABLE
SET search_path = ''
AS $$
  SELECT company_id FROM public.users WHERE id = auth.uid();
$$;

-- ============================================
-- 2. TABLE USERS
-- ============================================

CREATE TABLE IF NOT EXISTS public.users (
  id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  email TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('OWNER_ADMIN', 'ADMIN', 'DRIVER')),
  company_id UUID NOT NULL DEFAULT gen_random_uuid(),
  parent_user_id UUID REFERENCES public.users(id),
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (id)
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policies Users
DROP POLICY IF EXISTS "View Users Policy" ON public.users;
DROP POLICY IF EXISTS "Insert Users Policy" ON public.users;
DROP POLICY IF EXISTS "Delete Users Policy" ON public.users;
DROP POLICY IF EXISTS "Update Users Policy" ON public.users;

CREATE POLICY "View Users Policy" ON public.users FOR SELECT
USING (
  auth.uid() = id
  OR
  (get_my_role() IN ('OWNER_ADMIN', 'ADMIN') AND company_id = get_my_company_id())
);

CREATE POLICY "Insert Users Policy" ON public.users FOR INSERT
WITH CHECK (true);

CREATE POLICY "Delete Users Policy" ON public.users FOR DELETE
USING (get_my_role() = 'OWNER_ADMIN' AND company_id = get_my_company_id());

CREATE POLICY "Update Users Policy" ON public.users FOR UPDATE
USING (get_my_role() IN ('OWNER_ADMIN', 'ADMIN') AND company_id = get_my_company_id());

-- ============================================
-- 3. TABLE VEHICLES
-- ============================================

CREATE TABLE IF NOT EXISTS public.vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL,
  plate TEXT NOT NULL,
  model TEXT,
  type TEXT,
  km INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active',
  insurance_expiry DATE,
  tech_visit_expiry DATE,
  documents JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view vehicles of their company" ON public.vehicles;
DROP POLICY IF EXISTS "Owners/Admins can manage vehicles" ON public.vehicles;

CREATE POLICY "Users can view vehicles of their company" ON public.vehicles FOR SELECT
USING (company_id = get_my_company_id());

CREATE POLICY "Owners/Admins can manage vehicles" ON public.vehicles FOR ALL
USING (get_my_role() IN ('OWNER_ADMIN', 'ADMIN') AND company_id = get_my_company_id());

-- ============================================
-- 4. TABLE DRIVERS
-- ============================================

CREATE TABLE IF NOT EXISTS public.drivers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL,
  name TEXT NOT NULL,
  phone TEXT,
  license_type TEXT,
  status TEXT DEFAULT 'available',
  license_expiry DATE,
  medical_expiry DATE,
  documents JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "View drivers company" ON public.drivers;
DROP POLICY IF EXISTS "Manage drivers company" ON public.drivers;

CREATE POLICY "View drivers company" ON public.drivers FOR SELECT
USING (company_id = get_my_company_id());

CREATE POLICY "Manage drivers company" ON public.drivers FOR ALL
USING (get_my_role() IN ('OWNER_ADMIN', 'ADMIN') AND company_id = get_my_company_id());

-- ============================================
-- 5. TABLE ATTENDANCE (Avec primes + manual_bonus)
-- ============================================

CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL,
  driver_id BIGINT REFERENCES public.drivers(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  status TEXT NOT NULL,
  primes JSONB DEFAULT '{}'::jsonb,
  bonus INTEGER DEFAULT 0,
  manual_bonus NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT attendance_driver_date_unique UNIQUE (driver_id, date)
);

ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Manage attendance company" ON public.attendance;

CREATE POLICY "Manage attendance company" ON public.attendance FOR ALL
USING (company_id = get_my_company_id())
WITH CHECK (company_id = get_my_company_id());

-- ============================================
-- 6. STORAGE POLICIES
-- ============================================

INSERT INTO storage.buckets (id, name, public) 
VALUES ('documents', 'documents', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Access to Documents" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Users can Upload" ON storage.objects;
DROP POLICY IF EXISTS "Owners can Update/Delete Documents" ON storage.objects;
DROP POLICY IF EXISTS "Owners can Delete Documents" ON storage.objects;

CREATE POLICY "Public Access to Documents" ON storage.objects FOR SELECT
USING (bucket_id = 'documents');

CREATE POLICY "Authenticated Users can Upload" ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'documents' AND auth.role() = 'authenticated');

CREATE POLICY "Owners can Update/Delete Documents" ON storage.objects FOR UPDATE
USING (bucket_id = 'documents' AND auth.role() = 'authenticated');

CREATE POLICY "Owners can Delete Documents" ON storage.objects FOR DELETE
USING (bucket_id = 'documents' AND auth.role() = 'authenticated');

-- ============================================
-- 7. VÉRIFICATION FINALE
-- ============================================

SELECT 
  'Tables' as type,
  tablename as name,
  CASE WHEN rowsecurity THEN 'RLS Activé ✅' ELSE 'RLS Désactivé ⚠️' END as status
FROM pg_tables
WHERE schemaname = 'public'
  AND tablename IN ('users', 'vehicles', 'drivers', 'attendance')

UNION ALL

SELECT 
  'Functions' as type,
  routine_name as name,
  'Existe ✅' as status
FROM information_schema.routines
WHERE routine_schema = 'public'
  AND routine_name IN ('get_my_role', 'get_my_company_id')

ORDER BY type, name;

-- Résultat attendu :
-- - 4 tables avec "RLS Activé ✅"
-- - 2 fonctions
-- - 0 erreurs
